name: Theories (Comment)
on:
  issue_comment:
    type: [created]
jobs:
  theories:
    runs-on: ubuntu-20.04
    steps:
      - name: Check for magic word
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@test'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check out repository code
        uses: actions/checkout@v2
        if: steps.check.outputs.triggered == 'true'

      - name: Build theories
        run: docker run -v "$(pwd)":/work makarius/isabelle:Isabelle2021-1 build -D /work
        if: steps.check.outputs.triggered == 'true'
