name: Build thys
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'OUTDATED/**'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: makarius/isabelle:Isabelle2023
      options: "--entrypoint /bin/bash"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: /home/isabelle/Isabelle/bin/isabelle build -vD .
